# General MIDI Instrument Mapping
# Mirrors the frontend's instrument catalogue in src/data/instruments.ts

instruments = {
    "acoustic grand piano": 0, "piano": 0, "grand piano": 0,
    "bright acoustic piano": 1,
    "electric grand piano": 2,
    "honky-tonk piano": 3,
    "electric piano": 4, "rhodes": 4, "epiano": 4,
    "electric piano 2": 5,
    "harpsichord": 6,
    "clavinet": 7,
    "celesta": 8,
    "glockenspiel": 9,
    "music box": 10,
    "vibraphone": 11, "vibes": 11,
    "marimba": 12,
    "xylophone": 13,
    "tubular bells": 14, "bells": 14,
    "dulcimer": 15,
    "organ": 19, "church organ": 19,
    "hammond organ": 16,
    "accordion": 21,
    "harmonica": 22,
    "acoustic guitar": 24, "guitar": 24, "nylon guitar": 24,
    "steel guitar": 25, "acoustic guitar steel": 25,
    "jazz guitar": 26,
    "clean guitar": 27, "electric guitar": 27,
    "muted guitar": 28,
    "overdriven guitar": 29,
    "distortion guitar": 30, "distorted guitar": 30,
    "acoustic bass": 32, "upright bass": 32,
    "bass": 33, "electric bass": 33, "finger bass": 33,
    "pick bass": 34,
    "fretless bass": 35,
    "slap bass": 36,
    "synth bass": 38,
    "violin": 40,
    "viola": 41,
    "cello": 42,
    "contrabass": 43, "double bass": 43,
    "tremolo strings": 44,
    "pizzicato strings": 45,
    "harp": 46,
    "timpani": 47,
    "strings": 48, "string ensemble": 48, "orchestral strings": 48,
    "synth strings": 50,
    "choir": 52, "choir aahs": 52,
    "voice oohs": 53,
    "orchestra hit": 55,
    "trumpet": 56,
    "trombone": 57,
    "tuba": 58,
    "muted trumpet": 59,
    "french horn": 60, "horn": 60,
    "brass": 61, "brass section": 61,
    "synth brass": 62,
    "sax": 64, "soprano sax": 64,
    "alto sax": 65,
    "tenor sax": 66,
    "baritone sax": 67,
    "oboe": 68,
    "english horn": 69,
    "bassoon": 70,
    "clarinet": 71,
    "flute": 73,
    "piccolo": 72,
    "recorder": 74,
    "pan flute": 75,
    "synth lead": 80, "lead synth": 80,
    "synth pad": 88, "pad": 88,
    "warm pad": 89,
    "atmosphere": 99, "ambient pad": 99,
    "sitar": 104,
    "banjo": 105,
    "shamisen": 106,
    "koto": 107,
    "kalimba": 108,
    "bagpipe": 109,
    "fiddle": 110,
    "synth": 80, "keyboard": 0,
}
